### ISSUE TITLE
Limestone stacking not working

### ISSUE THREAD

**Issue by kurtzilla** [sachera/factorio-deadlocks-stacking-for-pyanodon#5]
Unable to stack limestone in v0.17.x 
When I insert limestone directly into a stacker (basic and stacker), I receive the message that "limestone cannot be smelted"

Not sure what info I need to provide to help solve the issue. Let me know what I can do to help

**Comment by sachera** [comment]
Was "Stacking-2" already researched?

**Comment by kurtzilla** [comment]
Thanks - that is probably the issue. Lost in Pyanodin :)

**Comment by sachera** [comment]
In this case i will close the issue. Feel free to reopen it if it was already researched.
